apiVersion: v1
kind: Service
metadata:
  name: k3s-agent
  labels:
    app: k3s-agent
    role: worker
spec:
  type: ClusterIP
  clusterIP: None  # Headless service for individual pod DNS
  selector:
    app: k3s-agent
    role: worker
  ports:
  - name: ssh
    port: 22
    targetPort: 22
    protocol: TCP
