apiVersion: v1
kind: ConfigMap
metadata:
  name: ssh-config
data:
  setup-ssh.sh: |
    #!/bin/sh
    set -e

    # Install OpenSSH server
    apk add --no-cache openssh-server openssh-client sudo

    # Create SSH directory
    mkdir -p /etc/ssh

    # Generate host keys if they don't exist
    ssh-keygen -A

    # Configure SSH for insecure access (practice only!)
    cat > /etc/ssh/sshd_config <<EOF
    Port 22
    PermitRootLogin yes
    PasswordAuthentication yes
    PubkeyAuthentication yes
    PermitEmptyPasswords no
    ChallengeResponseAuthentication no
    UsePAM no
    X11Forwarding no
    PrintMotd no
    AcceptEnv LANG LC_*
    Subsystem sftp /usr/lib/ssh/sftp-server
    EOF

    # Set root password to 'cka-practice' (INSECURE - for practice only!)
    echo "root:cka-practice" | chpasswd

    # Start SSH daemon
    /usr/sbin/sshd -D -e
