apiVersion: v1
kind: Service
metadata:
  name: ssh-bastion
  namespace: k8s-practice
  labels:
    app: ssh-bastion
spec:
  type: NodePort
  selector:
    app: ssh-bastion
  ports:
  - port: 22
    targetPort: 22
    nodePort: 30000
    protocol: TCP
    name: ssh
