apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ckad-a-2

bases:
  - ../../../base/ssh-bastion

namePrefix: ckad-a-2-

commonLabels:
  exam-type: ckad
  exam-set: a
  question-number: "2"

patches:
  - patch: |-
      - op: replace
        path: /metadata/name
        value: ckad-a-2
    target:
      kind: Namespace
  - patch: |-
      - op: replace
        path: /spec/ports/0/nodePort
        value: 30102
    target:
      kind: Service
      name: ssh-bastion
  - patch: |-
      - op: replace
        path: /data/CLUSTER_NAME
        value: kind-ckad-a-2
      - op: replace
        path: /data/EXAM_TYPE
        value: ckad
      - op: replace
        path: /data/CLUSTER_TYPE
        value: single-node
    target:
      kind: ConfigMap
      name: cluster-config
