version: '3.8'

services:
  kind-web-terminal:
    build: .
    container_name: kind-web-terminal
    ports:
      - "3000:3000"
    # Need privileged mode for Docker-in-Docker
    privileged: true
    volumes:
      # Persist Kind cluster data and Docker data inside the container
      - kind-data:/var/lib/docker
      - kube-data:/root/.kube
    environment:
      - PORT=3000
      - NODE_ENV=production
      - DOCKER_TLS_CERTDIR=/certs
    restart: unless-stopped
    # Storage driver for DinD
    security_opt:
      - seccomp=unconfined
    tmpfs:
      - /tmp

volumes:
  kind-data:
    driver: local
  kube-data:
    driver: local
