---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kind-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kube-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kind-web-terminal
  labels:
    app: kind-web-terminal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kind-web-terminal
  template:
    metadata:
      labels:
        app: kind-web-terminal
    spec:
      containers:
      - name: kind-web-terminal
        image: harbor.yourdomain.com/k8s-images/express-kind-node-pty-kind-web-terminal
        command: ["/bin/bash"]
        args: ["/scripts/start.sh"]
        ports:
        - containerPort: 3000
          name: express
          protocol: TCP
        - containerPort: 2222
          name: ssh-control
          protocol: TCP
        - containerPort: 2223
          name: ssh-worker
          protocol: TCP
        env:
        - name: PORT
          value: "3000"
        - name: NODE_ENV
          value: "production"
        - name: DOCKER_TLS_CERTDIR
          value: "/certs"
        securityContext:
          privileged: true
          seccompProfile:
            type: Unconfined
        volumeMounts:
        - name: kind-data
          mountPath: /var/lib/docker
        - name: kube-data
          mountPath: /root/.kube
        - name: tmp
          mountPath: /tmp
        - name: modules
          mountPath: /lib/modules
          readOnly: true
        - name: cgroup
          mountPath: /sys/fs/cgroup
        - name: start-script
          mountPath: /scripts
        resources:
          requests:
            memory: "6Gi"
            cpu: "2000m"
          limits:
            memory: "7Gi"
            cpu: "3000m"
      volumes:
      - name: kind-data
        persistentVolumeClaim:
          claimName: kind-data
      - name: kube-data
        persistentVolumeClaim:
          claimName: kube-data
      - name: tmp
        emptyDir:
          medium: Memory
      - name: modules
        hostPath:
          path: /lib/modules
          type: Directory
      - name: cgroup
        hostPath:
          path: /sys/fs/cgroup
          type: Directory
      - name: start-script
        configMap:
          name: start-script
          defaultMode: 0755
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: kind-web-terminal
  labels:
    app: kind-web-terminal
spec:
  type: NodePort
  selector:
    app: kind-web-terminal
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30000
    protocol: TCP
    name: express
  - port: 2222
    targetPort: 2222
    nodePort: 30222
    protocol: TCP
    name: ssh-control
  - port: 2223
    targetPort: 2223
    nodePort: 30223
    protocol: TCP
    name: ssh-worker
